export const API_ENDPOINTS = {
  //API ENDPOINTS
};

export const ACTION_TYPES = {
  AUTHORIZER: "AUTHORIZER",
  LOGGED_USER_DATA: "LOGGED_USER_DATA",
  SET_CHEFS: "SET_CHEFS",
  SET_CUISINES: "SET_CUISINES",
  SET_FOODS: "SET_FOODS",
  SET_NEARBY_SHOPS: "SET_NEARBY_SHOPS",
  SET_CHEF_FOODS: "SET_CHEF_FOODS",
  SET_CUISINES_LIST: "SET_CUISINES_LIST",
};
